name: osm
version: 1.0.0+1
description: Access Open Street Map data.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.19.0-0 <3.0.0"

dependencies:
  backstreets_widgets: ^0.0.5
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_osm_plugin: ^0.39.0
  flutter_riverpod: ^1.0.4
  geolocator: ^9.0.1
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
